### ISSUE TITLE
Multiple methods.

### ISSUE THREAD

**Issue by moderatorman** [QuarkTheAwesome/AMCSAPI#3]
This may be possible, but I'm not able to figure out how to start the chat connection in one method (Authenticate & Connect button) and send chat messages through another method (Send button)

Is there a way I can do this? Or would you have to update the API?
P.S: I would like to see you update this API. It has a lot of potential, and I'm planning on using it in many projects.

**Comment by moderatorman** [comment]
I'm not the best with Visual Basic, but is there a way to create a new Sub for each feature?
Example:
Public Sub auth(mc as New Server("localhost", 25565))

I know VB.NET won't let you use "New" in this context, but is this sort of thing possible with this API?
And if it isn't, I would like to suggest it get added in a new update.

**Comment by ashquarky** [comment]
I'm not completely sure what you mean - there's already a separate method for authentication. The idea behind the API is this:

```
Dim mc as New Server("localhost", 25565)
mc.authenticate("bla@bla.com", "passw0rd")
mc.startChatConnection()
```

Authenticate and connect are already in separate methods, and there's no reason you wouldn't be able to call these from different locations (buttons etc.)

**Comment by moderatorman** [comment]
What I'm trying to do is pass the API the IP and port later so it can give the user the ability to change the IP and port, without having to have a default IP and port in text boxes. This would also allow for better error handling than the default (the message box with the error and Continue/Quit buttons).
