### ISSUE TITLE
Getting server version.

### ISSUE THREAD

**Issue by moderatorman** [QuarkTheAwesome/AMCSAPI#4]
I know it says how to do it on the Wiki, but I can't really understand it. How am I supposed to get the server version, and say, put it in a label?

**Comment by ashquarky** [comment]
I'd do something like this:

```
Dim mc as New Server("localhost", 25565)
Dim serverInfo as ServerInformation
serverInfo = mc.getServerInfo()
LabelWhatever.Text = serverInfo.serverVersionName
```

**Comment by moderatorman** [comment]
Cool, thanks. For some reason my .NET has been acting up and a lot of the times my programs crash for no reason or will give me an error when I start them, so I thought that code wouldn't work because my program would start working after I removed it. I know that doesn't really make any sense but that's  roughly what happened when I tried to use this.
